/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the Collabora Office project.
 *
 * SPDX-License-Identifier: MPL-2.0
 */

#ifndef INCLUDED_SCADDINS_IDL_ORG_COLLABORAOFFICE_SHEET_ADDIN_PYTHONCOMPUTEFUNCTIONS_IDL
#define INCLUDED_SCADDINS_IDL_ORG_COLLABORAOFFICE_SHEET_ADDIN_PYTHONCOMPUTEFUNCTIONS_IDL

#include <org/collaboraoffice/sheet/addin/XPythonComputeFunctions.idl>

module org { module collaboraoffice { module sheet { module addin {

service PythonComputeFunctions
{
    interface XPythonComputeFunctions;
};

}; }; }; };

#endif
